env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - google
  - prettier
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - prettier
rules:
  {
    "prettier/prettier": ["error"],
    "react/react-in-jsx-scope": "off",
    "react/prop-types": ["off"],
  }
