name: Run tests

on:
  push:
    branches: [ main ]
  repository_dispatch:
    types: [ update ]
  workflow_dispatch:
  pull_request:
    branches: [ main ]

permissions:
  contents: write

jobs:
  test_tutorial_scripts:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: install pdfunite
        run: sudo apt-get install -y poppler-utils

      - name: install wkhtmltopdf
        run: sudo apt-get install -y wkhtmltopdf

      - name: install requirements
        run: |
          cd new-website
          cd utils
          pip install -r requirements.txt

      - name: Test tutorial fetching and export
        run: |
          cd new-website
          cd utils/tutorials
          python3 test_fetch_tutorials.py

      - name: test tutorials util functions
        run: |
          cd new-website
          cd utils/tutorials
          python3 test_utils.py

      - name: Test tutorials build pdf book functions
        run: |
          cd new-website
          cd utils/tutorials
          python3 test_build_pdf_book.py

      